version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tesouraria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tesouraria
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha-rede

volumes:
  mysql_data:

networks:
  minha-rede:
    driver: bridge
